// Generated by scripts/generate_contracts.py. Do not edit.
import { z } from "zod"

export const DecisionRecordSchema = z
  .object({
    decision_id: z.string().min(1),
    workspace_id: z.string().min(1),
    program_id: z.string().min(1).nullable(),
    item_id: z.string().min(1),
    computed_at: z.string().datetime(),
    causation_id: z.string().min(1),
    correlation_id: z.string().min(1),
    normalized_snapshot_id: z.string().min(1),
    normalized_snapshot_hash: z.string().length(64),
    source_revision_set: z
      .record(z.string(), z.string())
      .refine((revisions) => Object.keys(revisions).length > 0),
    graph_revision: z.string().min(1),
    policy_bundle_id: z.string().min(1),
    policy_bundle_hash: z.string().length(64),
    ranking_pipeline_hash: z.string().length(64),
    engine_version: z.string().min(1),
    normalization_profile_version: z.string().min(1),
    ready: z.boolean(),
    ranking_position: z.number().int().min(1),
  })
  .strict()

export type DecisionRecord = z.infer<typeof DecisionRecordSchema>
