// Generated by scripts/generate_contracts.py. Do not edit.
// Source: contracts/generated/evidence-record.schema.json
import { EvidenceRecordSchema } from "./evidence-record.generated"
import type { EvidenceRecord } from "./evidence-record.generated"

const SEMANTIC_RULES = {
  "defaults": {
    "artifacts": [],
    "release_stage": "pre_ga",
    "results": []
  },
  "duration": {
    "end": "invocation.end_time",
    "seconds": "invocation.duration_seconds",
    "start": "invocation.start_time",
    "tolerance_seconds": 0.001
  },
  "not_applicable_reason": {
    "min_length": 10,
    "status": "not_applicable"
  },
  "posix_relative_paths": [
    "invocation.working_directory",
    "artifacts[].path",
    "stdout_artifact.path",
    "stderr_artifact.path"
  ],
  "required_object_keys": [
    {
      "keys": [
        "os"
      ],
      "min_properties": 1,
      "path": "environment"
    }
  ],
  "version": "1.0.0"
} as const

export interface SemanticValidationError {
  readonly path: string
  readonly message: string
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === "object" && !Array.isArray(value)
}

function valuesAtPath(
  value: unknown,
  path: string,
): ReadonlyArray<{ readonly path: string; readonly value: unknown }> {
  const segments = path.split(".")
  let current: ReadonlyArray<{ readonly path: string; readonly value: unknown }> = [
    { path: "", value },
  ]
  for (const segment of segments) {
    const isArray = segment.endsWith("[]")
    const key = isArray ? segment.slice(0, -2) : segment
    const next: Array<{ readonly path: string; readonly value: unknown }> = []
    for (const entry of current) {
      if (!isRecord(entry.value)) continue
      const child = entry.value[key]
      const childPath = entry.path ? `${entry.path}.${key}` : key
      if (isArray) {
        if (!Array.isArray(child)) continue
        child.forEach((item, index) => {
          next.push({ path: `${childPath}[${index}]`, value: item })
        })
      } else {
        next.push({ path: childPath, value: child })
      }
    }
    current = next
  }
  return current
}

function valueAtPath(value: unknown, path: string): unknown {
  return valuesAtPath(value, path)[0]?.value
}

export function canonicalizeEvidenceRecord(
  record: EvidenceRecord,
): EvidenceRecord {
  return {
    ...record,
    release_stage: record.release_stage ?? SEMANTIC_RULES.defaults.release_stage,
    artifacts: record.artifacts ?? [...SEMANTIC_RULES.defaults.artifacts],
    results: record.results ?? [...SEMANTIC_RULES.defaults.results],
  }
}

export function validateEvidenceRecordSemantic(
  input: EvidenceRecord,
): SemanticValidationError[] {
  const record = canonicalizeEvidenceRecord(input)
  const errors: SemanticValidationError[] = []

  for (const path of SEMANTIC_RULES.posix_relative_paths) {
    for (const entry of valuesAtPath(record, path)) {
      if (typeof entry.value !== "string") continue
      if (entry.value.includes("\\") || entry.value.split("/").includes("..")) {
        errors.push({
          path: entry.path,
          message: `${entry.path} must be a contained POSIX relative path`,
        })
      }
    }
  }

  for (const rule of SEMANTIC_RULES.required_object_keys) {
    const value = valueAtPath(record, rule.path)
    if (!isRecord(value)) continue
    if (Object.keys(value).length < rule.min_properties) {
      errors.push({
        path: rule.path,
        message:
          `${rule.path} must contain at least ` +
          `${rule.min_properties} property`,
      })
    }
    for (const key of rule.keys) {
      if (!(key in value)) {
        errors.push({
          path: `${rule.path}.${key}`,
          message: `${rule.path} must include required key '${key}'`,
        })
      }
    }
  }

  const start = valueAtPath(record, SEMANTIC_RULES.duration.start)
  const end = valueAtPath(record, SEMANTIC_RULES.duration.end)
  const duration = valueAtPath(record, SEMANTIC_RULES.duration.seconds)
  if (
    typeof start === "string" &&
    typeof end === "string" &&
    typeof duration === "number"
  ) {
    const expected = (new Date(end).getTime() - new Date(start).getTime()) / 1000
    if (Math.abs(duration - expected) > SEMANTIC_RULES.duration.tolerance_seconds) {
      errors.push({
        path: SEMANTIC_RULES.duration.seconds,
        message:
          `duration_seconds (${duration}) does not match ` +
          `end_time - start_time (${expected})`,
      })
    }
  }

  if (record.status === "pass") {
    for (const result of record.results ?? []) {
      if (!result.passed) {
        errors.push({
          path: "status",
          message: `status is 'pass' but result '${result.kind}' has passed=false`,
        })
      }
    }
  }
  if (record.status === "fail" && record.invocation.exit_code === 0) {
    if (!(record.results ?? []).some((result) => !result.passed)) {
      errors.push({
        path: "status",
        message: "status is 'fail' with exit_code=0 but no result has passed=false",
      })
    }
  }

  if (
    record.status === SEMANTIC_RULES.not_applicable_reason.status &&
    record.applicability_reason.trim().length <
      SEMANTIC_RULES.not_applicable_reason.min_length
  ) {
    errors.push({
      path: "applicability_reason",
      message:
        "applicability_reason for not_applicable must contain at least " +
        `${SEMANTIC_RULES.not_applicable_reason.min_length} characters`,
    })
  }
  return errors
}

export function isEvidenceRecordValid(data: unknown): boolean {
  const parsed = EvidenceRecordSchema.safeParse(data)
  return parsed.success && validateEvidenceRecordSemantic(parsed.data).length === 0
}
