// Generated by scripts/generate_contracts.py. Do not edit.
import { z } from "zod"

export const SetupProfileSchema = z.enum(["development", "production"])
export const CapabilityNameSchema = z.enum([
  "local_runtime",
  "github_integration",
  "release_certification",
  "production_cutover",
])
export const CheckStateSchema = z.enum([
  "ready",
  "repairable",
  "needs_input",
  "blocked",
  "not_required",
])
export const ActionStateSchema = z.enum([
  "pending",
  "running",
  "applied",
  "verified",
  "failed",
  "compensating",
  "compensated",
  "manual_recovery_required",
])
const ScalarSchema = z.union([z.string(), z.number(), z.boolean(), z.null()])
export const DetectionCheckSchema = z.object({
  check_id: z.string(),
  state: CheckStateSchema,
  summary: z.string(),
  impact: z.string(),
  remediation: z.array(z.string()).default([]),
  evidence: z.record(z.string(), ScalarSchema).default({}),
}).strict()
export const DetectionSnapshotSchema = z.object({
  snapshot_id: z.string(),
  profile: SetupProfileSchema,
  config_revision: z.string(),
  checks: z.array(DetectionCheckSchema),
}).strict()
export const SetupActionSchema = z.object({
  action_id: z.string(),
  title: z.string(),
  reason: z.string(),
  risk: z.enum(["low", "medium", "high"]),
  reversible: z.boolean(),
  depends_on: z.array(z.string()),
  kind: z.string(),
  parameters: z.record(z.string(), ScalarSchema),
}).strict()
export const SetupPlanSchema = z.object({
  plan_id: z.string(),
  profile: SetupProfileSchema,
  detection_snapshot_id: z.string(),
  config_revision: z.string(),
  actions: z.array(SetupActionSchema),
}).strict()
export const ActionResultSchema = z.object({
  action_id: z.string(),
  state: ActionStateSchema,
  message: z.string(),
  redacted_evidence: z.record(z.string(), ScalarSchema).default({}),
}).strict()
export const CapabilityReportSchema = z.object({
  capability: CapabilityNameSchema,
  state: CheckStateSchema,
  reason: z.string(),
  impact: z.string(),
  next_actions: z.array(z.string()),
  supporting_check_ids: z.array(z.string()),
}).strict()
export const SetupEnvelopeSchema = z.object({
  session_id: z.string().nullable().optional(),
  detection: DetectionSnapshotSchema.nullable().optional(),
  plan: SetupPlanSchema.nullable().optional(),
  capabilities: z.array(CapabilityReportSchema).default([]),
  results: z.array(ActionResultSchema).default([]),
}).strict()

export type SetupProfile = z.infer<typeof SetupProfileSchema>
export type DetectionCheck = z.infer<typeof DetectionCheckSchema>
export type DetectionSnapshot = z.infer<typeof DetectionSnapshotSchema>
export type SetupAction = z.infer<typeof SetupActionSchema>
export type SetupPlan = z.infer<typeof SetupPlanSchema>
export type ActionResult = z.infer<typeof ActionResultSchema>
export type CapabilityReport = z.infer<typeof CapabilityReportSchema>
export type SetupEnvelope = z.infer<typeof SetupEnvelopeSchema>
