"""Generate deterministic JSON Schema and TypeScript artifacts from Pydantic."""

from __future__ import annotations

import hashlib
import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Final, cast

from work_frontier.contracts import DecisionRecordContract
from work_frontier.contracts.evidence_record import EvidenceRecord

CHECK_ARGUMENT: Final = "--check"
CONTRACT_DIRECTORY: Final = Path("contracts/generated")
JSON_SCHEMA_PATH: Final = CONTRACT_DIRECTORY / "decision-record.schema.json"
EVIDENCE_SCHEMA_PATH: Final = CONTRACT_DIRECTORY / "evidence-record.schema.json"
ZOD_PATH: Final = Path("frontend/src/contracts/decision-record.generated.ts")
ZOD_EVIDENCE_PATH: Final = Path("frontend/src/contracts/evidence-record.generated.ts")
SEMANTIC_EVIDENCE_PATH: Final = Path(
    "frontend/src/contracts/evidence-record-semantic.generated.ts"
)
FALLBACK_RECEIPT_PATH: Final = Path(".omo/evidence/static/contracts.json")


def json_schema() -> str:
    """Return canonical serialized Pydantic JSON Schema for DecisionRecord."""
    schema = DecisionRecordContract.model_json_schema()
    return f"{json.dumps(schema, indent=2, sort_keys=True)}\n"


def evidence_schema() -> str:
    """Return canonical serialized Pydantic JSON Schema for EvidenceRecord."""
    schema = EvidenceRecord.model_json_schema()
    return f"{json.dumps(schema, indent=2, sort_keys=True)}\n"


def _zod_source(schema_content: str, source_path: Path, schema_name: str) -> str:
    """Generate Zod source by calling x-to-zod on Pydantic-derived schema."""
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".json", delete=False
    ) as schema_tmp:
        _ = schema_tmp.write(schema_content)
        schema_path = Path(schema_tmp.name)

    with tempfile.NamedTemporaryFile(mode="w", suffix=".ts", delete=False) as zod_tmp:
        zod_path = Path(zod_tmp.name)

    try:
        _ = subprocess.run(
            [
                "node",
                "scripts/generate_zod_from_schema.mjs",
                str(schema_path),
                str(zod_path),
                schema_name,
            ],
            check=True,
            capture_output=True,
            text=True,
        )
        content = zod_path.read_text(encoding="utf-8")
        return content.replace(str(schema_path), str(source_path))
    finally:
        _ = schema_path.unlink(missing_ok=True)
        _ = zod_path.unlink(missing_ok=True)


def zod_source() -> str:
    """Return generated DecisionRecord Zod source."""
    return _zod_source(json_schema(), JSON_SCHEMA_PATH, "DecisionRecordSchema")


def evidence_zod_source() -> str:
    """Return generated EvidenceRecord structural Zod source."""
    return _zod_source(evidence_schema(), EVIDENCE_SCHEMA_PATH, "EvidenceRecordSchema")


def evidence_semantic_source() -> str:
    """Generate EvidenceRecord semantic validation from Pydantic rule metadata."""
    schema = EvidenceRecord.model_json_schema()
    raw_rules = schema.get("x-work-frontier-semantic-rules")
    if not isinstance(raw_rules, dict):
        msg = "EvidenceRecord schema is missing x-work-frontier-semantic-rules"
        raise TypeError(msg)
    rules = cast("dict[str, object]", raw_rules)
    rules_json = json.dumps(rules, indent=2, sort_keys=True)
    return f"""// Generated by scripts/generate_contracts.py. Do not edit.
// Source: {EVIDENCE_SCHEMA_PATH}
import {{ EvidenceRecordSchema }} from "./evidence-record.generated"
import type {{ EvidenceRecord }} from "./evidence-record.generated"

const SEMANTIC_RULES = {rules_json} as const

export interface SemanticValidationError {{
  readonly path: string
  readonly message: string
}}

function isRecord(value: unknown): value is Record<string, unknown> {{
  return value !== null && typeof value === "object" && !Array.isArray(value)
}}

function valuesAtPath(
  value: unknown,
  path: string,
): ReadonlyArray<{{ readonly path: string; readonly value: unknown }}> {{
  const segments = path.split(".")
  let current: ReadonlyArray<{{ readonly path: string; readonly value: unknown }}> = [
    {{ path: "", value }},
  ]
  for (const segment of segments) {{
    const isArray = segment.endsWith("[]")
    const key = isArray ? segment.slice(0, -2) : segment
    const next: Array<{{ readonly path: string; readonly value: unknown }}> = []
    for (const entry of current) {{
      if (!isRecord(entry.value)) continue
      const child = entry.value[key]
      const childPath = entry.path ? `${{entry.path}}.${{key}}` : key
      if (isArray) {{
        if (!Array.isArray(child)) continue
        child.forEach((item, index) => {{
          next.push({{ path: `${{childPath}}[${{index}}]`, value: item }})
        }})
      }} else {{
        next.push({{ path: childPath, value: child }})
      }}
    }}
    current = next
  }}
  return current
}}

function valueAtPath(value: unknown, path: string): unknown {{
  return valuesAtPath(value, path)[0]?.value
}}

export function canonicalizeEvidenceRecord(
  record: EvidenceRecord,
): EvidenceRecord {{
  return {{
    ...record,
    release_stage: record.release_stage ?? SEMANTIC_RULES.defaults.release_stage,
    artifacts: record.artifacts ?? [...SEMANTIC_RULES.defaults.artifacts],
    results: record.results ?? [...SEMANTIC_RULES.defaults.results],
  }}
}}

export function validateEvidenceRecordSemantic(
  input: EvidenceRecord,
): SemanticValidationError[] {{
  const record = canonicalizeEvidenceRecord(input)
  const errors: SemanticValidationError[] = []

  for (const path of SEMANTIC_RULES.posix_relative_paths) {{
    for (const entry of valuesAtPath(record, path)) {{
      if (typeof entry.value !== "string") continue
      if (entry.value.includes("\\\\") || entry.value.split("/").includes("..")) {{
        errors.push({{
          path: entry.path,
          message: `${{entry.path}} must be a contained POSIX relative path`,
        }})
      }}
    }}
  }}

  for (const rule of SEMANTIC_RULES.required_object_keys) {{
    const value = valueAtPath(record, rule.path)
    if (!isRecord(value)) continue
    if (Object.keys(value).length < rule.min_properties) {{
      errors.push({{
        path: rule.path,
        message:
          `${{rule.path}} must contain at least ` +
          `${{rule.min_properties}} property`,
      }})
    }}
    for (const key of rule.keys) {{
      if (!(key in value)) {{
        errors.push({{
          path: `${{rule.path}}.${{key}}`,
          message: `${{rule.path}} must include required key '${{key}}'`,
        }})
      }}
    }}
  }}

  const start = valueAtPath(record, SEMANTIC_RULES.duration.start)
  const end = valueAtPath(record, SEMANTIC_RULES.duration.end)
  const duration = valueAtPath(record, SEMANTIC_RULES.duration.seconds)
  if (
    typeof start === "string" &&
    typeof end === "string" &&
    typeof duration === "number"
  ) {{
    const expected = (new Date(end).getTime() - new Date(start).getTime()) / 1000
    if (Math.abs(duration - expected) > SEMANTIC_RULES.duration.tolerance_seconds) {{
      errors.push({{
        path: SEMANTIC_RULES.duration.seconds,
        message:
          `duration_seconds (${{duration}}) does not match ` +
          `end_time - start_time (${{expected}})`,
      }})
    }}
  }}

  if (record.status === "pass") {{
    for (const result of record.results ?? []) {{
      if (!result.passed) {{
        errors.push({{
          path: "status",
          message: `status is 'pass' but result '${{result.kind}}' has passed=false`,
        }})
      }}
    }}
  }}
  if (record.status === "fail" && record.invocation.exit_code === 0) {{
    if (!(record.results ?? []).some((result) => !result.passed)) {{
      errors.push({{
        path: "status",
        message: "status is 'fail' with exit_code=0 but no result has passed=false",
      }})
    }}
  }}

  if (
    record.status === SEMANTIC_RULES.not_applicable_reason.status &&
    record.applicability_reason.trim().length <
      SEMANTIC_RULES.not_applicable_reason.min_length
  ) {{
    errors.push({{
      path: "applicability_reason",
      message:
        "applicability_reason for not_applicable must contain at least " +
        `${{SEMANTIC_RULES.not_applicable_reason.min_length}} characters`,
    }})
  }}
  return errors
}}

export function isEvidenceRecordValid(data: unknown): boolean {{
  const parsed = EvidenceRecordSchema.safeParse(data)
  return parsed.success && validateEvidenceRecordSemantic(parsed.data).length === 0
}}
"""


def expected_artifacts() -> tuple[tuple[Path, str], ...]:
    """Return every generated artifact and its expected deterministic content."""
    return (
        (JSON_SCHEMA_PATH, json_schema()),
        (EVIDENCE_SCHEMA_PATH, evidence_schema()),
        (ZOD_PATH, zod_source()),
        (ZOD_EVIDENCE_PATH, evidence_zod_source()),
        (SEMANTIC_EVIDENCE_PATH, evidence_semantic_source()),
    )


def artifacts_are_current() -> bool:
    """Return whether checked-in artifacts match the canonical contract model."""
    return all(
        path.exists() and path.read_text(encoding="utf-8") == content
        for path, content in expected_artifacts()
    )


def write_artifacts() -> None:
    """Write deterministic generated contract artifacts."""
    for path, content in expected_artifacts():
        path.parent.mkdir(parents=True, exist_ok=True)
        _ = path.write_text(content, encoding="utf-8")


def _sha256(content: str) -> str:
    return hashlib.sha256(content.encode("utf-8")).hexdigest()


def _write_receipt(*, check_mode: bool, exit_code: int) -> None:
    """Write a producer receipt; the outer harness runner owns EvidenceRecord."""
    configured = os.environ.get("WF_HARNESS_ARTIFACT")
    path = Path(configured) if configured else FALLBACK_RECEIPT_PATH
    path.parent.mkdir(parents=True, exist_ok=True)
    receipt = {
        "schema_version": "1.0.0",
        "kind": "contract_generation_receipt",
        "mode": "check" if check_mode else "generate",
        "exit_code": exit_code,
        "passed": exit_code == 0,
        "artifacts": [
            {
                "path": str(artifact_path),
                "sha256": _sha256(content),
                "current": artifact_path.exists()
                and artifact_path.read_text(encoding="utf-8") == content,
            }
            for artifact_path, content in expected_artifacts()
        ],
    }
    temporary = path.with_suffix(f"{path.suffix}.tmp")
    _ = temporary.write_text(
        f"{json.dumps(receipt, indent=2, sort_keys=True)}\n", encoding="utf-8"
    )
    temporary.replace(path)


def main(arguments: list[str]) -> int:
    """Generate artifacts or report whether checked-in artifacts drifted."""
    check_mode = len(arguments) == 1 and arguments[0] == CHECK_ARGUMENT
    if not check_mode and arguments:
        print("usage: generate_contracts.py [--check]", file=sys.stderr)
        return 2

    if check_mode:
        exit_code = 0 if artifacts_are_current() else 1
    else:
        write_artifacts()
        exit_code = 0
    _write_receipt(check_mode=check_mode, exit_code=exit_code)
    return exit_code


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
