#!/usr/bin/env node

/**
 * Generate Zod schema from JSON Schema using x-to-zod.
 *
 * Usage: node generate_zod_from_schema.mjs <input.schema.json> <output.ts> <SchemaName>
 *
 * This script replaces the hand-coded zod_source() function in generate_contracts.py,
 * ensuring Zod schemas are always derived from the canonical JSON Schema.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { jsonSchemaToZod } from "x-to-zod";

const [,, inputPath, outputPath, schemaName] = process.argv;

if (!inputPath || !outputPath || !schemaName) {
  console.error("Usage: generate_zod_from_schema.mjs <input.schema.json> <output.ts> <SchemaName>");
  process.exit(1);
}

try {
  const jsonSchema = JSON.parse(readFileSync(inputPath, "utf-8"));

  let zodCode = jsonSchemaToZod(jsonSchema, {
    module: "esm",
    name: schemaName,
    zodVersion: "v3",
  });

  // Strip the import line from x-to-zod output (we add our own header)
  zodCode = zodCode.replace(/^import \{ z \} from "zod"\s*\n?/m, "");

  // Post-process: add minProperties refinements from JSON Schema
  zodCode = addMinPropertiesRefinements(zodCode, jsonSchema);

  // Re-format the z.object with each field on its own line for readability
  zodCode = formatObjectFields(zodCode);

  const output = `// Generated by scripts/generate_zod_from_schema.mjs. Do not edit.
// Source: ${inputPath}
import { z } from "zod"

${zodCode}

export type ${schemaName.replace("Schema", "")} = z.infer<typeof ${schemaName}>
`;

  writeFileSync(outputPath, output);
  console.log(`Generated ${outputPath}`);
} catch (error) {
  console.error(`Error: ${error.message}`);
  process.exit(1);
}

/**
 * Find the position immediately after the closing paren that matches
 * the opening paren at `openPos`.
 */
function findMatchingCloseParen(code, openPos) {
  let depth = 0;
  for (let i = openPos; i < code.length; i++) {
    if (code[i] === "(") depth++;
    else if (code[i] === ")") {
      depth--;
      if (depth === 0) return i + 1;
    }
  }
  return -1;
}

/**
 * Walk JSON Schema properties looking for minProperties constraints.
 * For each record/map property with minProperties, append a .refine() call
 * immediately after the z.record(...) expression.
 */
function addMinPropertiesRefinements(zodCode, jsonSchema) {
  if (!jsonSchema.properties) return zodCode;

  for (const [propName, propSchema] of Object.entries(jsonSchema.properties)) {
    if (propSchema.type === "object" && propSchema.minProperties !== undefined) {
      const min = propSchema.minProperties;

      // Find the needle: "propName": z.record(
      const needle = `"${propName}": z.record(`;
      const pos = zodCode.indexOf(needle);
      if (pos === -1) continue;

      // The open paren of z.record( is at pos + needle.length - 1
      const openParenPos = pos + needle.length - 1;
      const closeEnd = findMatchingCloseParen(zodCode, openParenPos);
      if (closeEnd === -1) continue;

      // Insert .refine(...) right after the closing paren of z.record(...)
      const refine = `.refine((obj) => Object.keys(obj).length >= ${min}, { message: "Must have at least ${min} ${propName.replace(/_/g, " ")}" })`;
      zodCode = zodCode.slice(0, closeEnd) + refine + zodCode.slice(closeEnd);
    }
  }
  return zodCode;
}

/**
 * Format z.object fields so each property is on its own line.
 */
function formatObjectFields(zodCode) {
  return zodCode.replace(
    /z\.object\(\{(.+?)\}\)/gs,
    (_match, body) => {
      const fields = body
        .split(/,\s*(?=")/)
        .map((f) => f.trim())
        .filter(Boolean);
      if (fields.length <= 3) return `z.object({ ${fields.join(", ")} })`;
      const indented = fields.map((f) => `    ${f}`).join(",\n");
      return `z.object({\n${indented},\n  })`;
    },
  );
}
