"""Generate deterministic JSON Schema and Zod artifacts from Pydantic contracts."""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Final

from work_frontier.contracts import DecisionRecordContract

CHECK_ARGUMENT: Final = "--check"
CONTRACT_DIRECTORY: Final = Path("contracts/generated")
JSON_SCHEMA_PATH: Final = CONTRACT_DIRECTORY / "decision-record.schema.json"
ZOD_PATH: Final = Path("frontend/src/contracts/decision-record.generated.ts")


def json_schema() -> str:
    """Return canonical serialized Pydantic JSON Schema."""
    schema = DecisionRecordContract.model_json_schema()
    return f"{json.dumps(schema, indent=2, sort_keys=True)}\n"


def zod_source() -> str:
    """Return the Zod source derived from canonical DecisionRecord fields."""
    return (
        "// Generated by scripts/generate_contracts.py. Do not edit.\n"
        'import { z } from "zod"\n'
        "\n"
        "export const DecisionRecordSchema = z\n"
        "  .object({\n"
        "    decision_id: z.string().min(1),\n"
        "    workspace_id: z.string().min(1),\n"
        "    program_id: z.string().min(1).nullable(),\n"
        "    item_id: z.string().min(1),\n"
        "    computed_at: z.string().datetime(),\n"
        "    causation_id: z.string().min(1),\n"
        "    correlation_id: z.string().min(1),\n"
        "    normalized_snapshot_id: z.string().min(1),\n"
        "    normalized_snapshot_hash: z.string().length(64),\n"
        "    source_revision_set: z\n"
        "      .record(z.string(), z.string())\n"
        "      .refine((revisions) => Object.keys(revisions).length > 0),\n"
        "    graph_revision: z.string().min(1),\n"
        "    policy_bundle_id: z.string().min(1),\n"
        "    policy_bundle_hash: z.string().length(64),\n"
        "    ranking_pipeline_hash: z.string().length(64),\n"
        "    engine_version: z.string().min(1),\n"
        "    normalization_profile_version: z.string().min(1),\n"
        "    ready: z.boolean(),\n"
        "    ranking_position: z.number().int().min(1),\n"
        "  })\n"
        "  .strict()\n"
        "\n"
        "export type DecisionRecord = z.infer<typeof DecisionRecordSchema>\n"
    )


def expected_artifacts() -> tuple[tuple[Path, str], ...]:
    """Return every generated artifact and its expected deterministic content."""
    return ((JSON_SCHEMA_PATH, json_schema()), (ZOD_PATH, zod_source()))


def artifacts_are_current() -> bool:
    """Return whether checked-in artifacts match the canonical contract model."""
    return all(
        path.exists() and path.read_text(encoding="utf-8") == content
        for path, content in expected_artifacts()
    )


def write_artifacts() -> None:
    """Write deterministic generated contract artifacts."""
    for path, content in expected_artifacts():
        _ = path.parent.mkdir(parents=True, exist_ok=True)
        _ = path.write_text(content, encoding="utf-8")


def main(arguments: list[str]) -> int:
    """Generate artifacts or report whether checked-in artifacts drifted."""
    match arguments:
        case []:
            write_artifacts()
            return 0
        case [argument] if argument == CHECK_ARGUMENT:
            return 0 if artifacts_are_current() else 1
        case _:
            print("usage: generate_contracts.py [--check]", file=sys.stderr)
            return 2


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
