#!/usr/bin/env node

/** Generate a structural Zod schema from canonical JSON Schema. */

import { readFileSync, writeFileSync } from "node:fs";
import { jsonSchemaToZod } from "x-to-zod";

import {
  collectRecordConstraints,
  renderRecordConstraintRefinement,
} from "./zod_record_constraints.mjs";

const [,, inputPath, outputPath, schemaName] = process.argv;

if (!inputPath || !outputPath || !schemaName) {
  console.error("Usage: generate_zod_from_schema.mjs <input.schema.json> <output.ts> <SchemaName>");
  process.exit(1);
}

function resolveRefs(schema, defs = null) {
  if (defs === null) defs = schema.$defs || {};
  if (schema == null || typeof schema !== "object") return schema;
  if (Array.isArray(schema)) return schema.map((item) => resolveRefs(item, defs));
  if (schema.$ref && typeof schema.$ref === "string" && schema.$ref.startsWith("#/$defs/")) {
    const defName = schema.$ref.slice("#/$defs/".length);
    if (!defs[defName]) throw new Error(`Unresolvable $ref: ${schema.$ref}`);
    return resolveRefs(structuredClone(defs[defName]), defs);
  }
  return Object.fromEntries(
    Object.entries(schema).map(([key, value]) => [key, resolveRefs(value, defs)]),
  );
}

function formatObjectFields(zodCode) {
  return zodCode.replace(/z\.object\(\{(.+?)\}\)/gs, (_match, body) => {
    const fields = body
      .split(/,\s*(?=")/)
      .map((field) => field.trim())
      .filter(Boolean);
    if (fields.length <= 3) return `z.object({ ${fields.join(", ")} })`;
    return `z.object({\n${fields.map((field) => `    ${field}`).join(",\n")},\n  })`;
  });
}

try {
  const rawSchema = JSON.parse(readFileSync(inputPath, "utf-8"));
  const jsonSchema = resolveRefs(rawSchema);
  const recordConstraints = collectRecordConstraints(jsonSchema);
  const generatedSchemaName = recordConstraints.length > 0
    ? `${schemaName}Base`
    : schemaName;
  let zodCode = jsonSchemaToZod(jsonSchema, {
    module: "esm",
    name: generatedSchemaName,
    zodVersion: "v3",
  });
  zodCode = zodCode.replace(/^import \{ z \} from "zod"\s*\n?/m, "");
  zodCode = formatObjectFields(zodCode);
  const refinement = renderRecordConstraintRefinement(
    schemaName,
    generatedSchemaName,
    recordConstraints,
  );
  if (refinement) zodCode = `${zodCode}\n\n${refinement}`;

  const output = `// Generated by scripts/generate_zod_from_schema.mjs. Do not edit.
// Source: ${inputPath}
import { z } from "zod"

${zodCode}

export type ${schemaName.replace("Schema", "")} = z.infer<typeof ${schemaName}>
`;
  writeFileSync(outputPath, output);
  console.log(`Generated ${outputPath}`);
} catch (error) {
  console.error(`Error: ${error.message}`);
  process.exit(1);
}
